apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: knb5lzy09-python 
  janus-idp.io/tekton: knb5lzy09-python
  backstage.io/kubernetes-id: knb5lzy09-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: knb5lzy09-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  